### ISSUE TITLE
Deployment with scope: subscription fails

### ISSUE THREAD

**Issue by kanika1894** [whiteducksoftware/azure-arm-action-js#12]
![image](https://user-images.githubusercontent.com/58769601/91279913-b9bbce80-e7a3-11ea-9e51-70013c796e4a.png)

It is failing in all the following scenarios :
1. Providing template as URL
2. Copying the template asnd providing the location as examples/template/template.json 
3. Providing default parameters in the template
4. Providing parameters file
5. Providing inline parameters

Also, with the same template, using Az cli, the deployment is successful
Used the following command :
az deployment sub create --name demosubdeployment --location centralus --template-uri  "https://raw.githubusercontent.com/Azure/azure-docs-json-samples/master/azure-resource-manager/emptyRG.json" --parameters rgName=demoRg rgLocation=centralus

**Comment by nmeisenzahl** [comment]
@StiviiK can you please have a look into this?

**Comment by StiviiK** [comment]
How does your action step in the yaml look like?

**Comment by kanika1894** [comment]
One of them
```
on: [push]
name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: kpTestOrg/ARMtesting@master
      id: deploy
      with:
        scope: subscription
        subscriptionId: c00d16c7-****-****-****-************
        location: centralus               
        templateLocation: examples/template/template.json
        parameters: examples/template/parameters.json
```
